name: Build and Release Tweak

on:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "control"
  workflow_dispatch:

jobs:
  build:
    name: Build tweak
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install gmake
        run: brew install make

      - name: Install theos/theos
        run: bash -c "$(curl -fsSL 'https://raw.githubusercontent.com/theos/theos/master/bin/install-theos')"

      - name: Setup Theos environment
        run: echo "THEOS=/Users/runner/theos" >> $GITHUB_ENV

      - name: Make separate packages directory
        run: mkdir ~/debs/

      - name: Build ding rootful
        run: |
          gmake -j$(sysctl -n hw.ncpu) clean
          gmake -j$(sysctl -n hw.ncpu) do ROOTFUL=1 SYSROOT=$THEOS/sdks/iPhoneOS16.5.sdk
        continue-on-error: true

      - name: Move rootful .deb
        run: mv ./packages/*.deb ~/debs/
      
      - name: Build ding rootless
        run: |
          gmake -j$(sysctl -n hw.ncpu) clean
          gmake -j$(sysctl -n hw.ncpu) do SYSROOT=$THEOS/sdks/iPhoneOS16.5.sdk
        continue-on-error: true

      - name: Move rootless .deb
        run: mv ./packages/*.deb ~/debs/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ding
          path: ~/debs/*.deb

      - name: Delete old release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Get artifacts
        uses: actions/download-artifact@v3
        with:
          name: ding
          path: ./artifacts/

      - name: Create new rolling release
        uses: ncipollo/release-action@v1
        with:
          name: "Ding Release"
          body: "`itsnebulalol/ding` built with GitHub Actions.\n\nRead the `README.md` to determine what changes were made, as per the `LICENSE`."
          artifacts: "./artifacts/*.deb"
          tag: release
          token: ${{ secrets.GITHUB_TOKEN }}
